### ISSUE TITLE
Remote Participant View not rendered in iOS app

### ISSUE THREAD

**Issue by yaalisri** [Azure-Samples/communication-services-ios-calling-hero#54] opened 2021-06-24 09:30 UTC
I tried running this sample app replacing the token with our Communication Service token. I am able to install the app on 2 devices and test the call by creating a call and sharing the call id to another device. 
I can see the audio works properly on both devices but the remote video is not rendered on any of the device.

**Comment by waynemo** [comment] 2021-06-29 23:13
@yaalisri we appreciate the feedback. To help look into the issue further could you please provide some additional information?

- The specific commit used to run the app.
- Detailed steps to reproduce the issue. Screenshots and/or screen recordings would be helpful as well.
- Type of devices and iOS versions.

Thanks.

**Comment by AmyL219** [comment] 2021-06-30 00:00
Have you granted the video permission by toggling the video button either from setup view or calling view?
![Simulator Screen Shot - iPhone 11 - 2021-03-02 at 22 52 32](https://user-images.githubusercontent.com/75647512/123882381-8b46dc80-d8fb-11eb-8990-92a74cdcdfc3.png)

**Comment by AmyL219** [comment] 2022-01-06 22:51
Close the issue since there is no following comment. 
Will reopen the ticket if this problem shows up again.

**Closed by AmyL219** 2022-01-06 22:51 UTC
